Test GitVersion on feature branch

diff --git a/infrastructure/infra-deployment.yml b/infrastructure/infra-deployment.yml
--- a/infrastructure/infra-deployment.yml
+++ b/infrastructure/infra-deployment.yml
@@ -42,8 +42,8 @@ stages:
  - stage: Validate 
    displayName: Run Validate
    jobs: 
-    - job:
-      displayName:
+    - job: ValidateJob
+      displayName: Validate
       steps:
        - checkout: self
        - task: AzureCli@2
@@ -61,18 +61,40 @@ stages:
  - stage: Deploy 
    displayName: Run Deploy
    jobs:    
-    - job:
-      displayName:
+    - job: DeployJob
+      displayName: Deploy Job
       steps:
        - checkout: self
+        # Install GitVersion
+       - task: gitversion/setup@0
+         displayName: Install GitVersion
+         inputs:
+          versionSpec: "5.x"
+
+       - task: GitVersion@5
+         displayName: 'Get Version'
+         inputs:
+           runtime: 'netcore'  # Adjust if needed
+           configFilePath: '.azuredevops/gitversion.yml'
+         name: GetVersion  # Naming the task for later reference
+
        - task: AzureCli@2
-        name: Deploying
-        displayName: Deploying
-        inputs:
-         azureSubscription: $(serviceConnectionName)
-         scriptType: 'bash'
-         scriptLocation: 'inlineScript'
-         inlineScripts: |
-           az deployment group create --resource-group$(resourceGroupName) \
-           --template-file ../../bicep/main/main-infra.bicep \
-           --parameters ../../env/${{parameters.enviorment}}/params-infra.json     
+         name: Deploying
+         displayName: Deploying
+         inputs:
+          azureSubscription: $(serviceConnectionName)
+          scriptType: 'bash'
+          scriptLocation: 'inlineScript'
+          inlineScripts: |
+           az deployment group create --resource-group$(resourceGroupName) --template-file ../../bicep/main/main-infra.bicep --parameters ../../env/${{parameters.enviorment}}/params-infra.json
+           # Capture the result of the deployment
+            if [ $? -eq 0 ]; then
+              echo "Deployment succeeded."
+              echo "Current Version: $(GitVersion.SemVer)"  # Print current version
+              
+              # Increment version logic here
+              echo "Incrementing version..."
+              # Call a script or command to update the version in GitVersion.yml or wherever it is stored.
+            else
+              echo "Deployment failed, version not incremented."
+            fi
